version: "3"
services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    # network_mode: host
    networks:
      - keycloak-network
    ports:
      - 1025:1025
      - 8025:8025
  database:
    image: mysql:8
    restart: unless-stopped
    # network_mode: host
    networks:
      - keycloak-network
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: secret
  keycloak:
    build: keycloak
    restart: unless-stopped
    # network_mode: host
    networks:
      - keycloak-network
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: mysql
      DB_ADDR: database
      DB_PORT: 3306
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_DATABASE: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  js-console:
    build: js-console
    restart: unless-stopped
    # network_mode: host
    networks:
      - keycloak-network
    ports:
      - 8000:80

networks:
  keycloak-network:
    driver: bridge
